commands:
  personnel: "personnel"

permissions:
  member: "staff.member"
  command:
    reload: "staffnetwork.command.reload"
    personnel: "staffnetwork.command.personnel"

messages:
  personnel:
    header: |
      &b-
      &bStaff Online
    server-line: '&c%server%:'
    player-line: '&c| &6%name%'
    footer: '&b-'
    no-results: |-
      &c-
      &cNo staff online
      &c-

personnel-module:
  # Determines if the plugin should hook into the vanish-module of the core plugin
  # Only works if you are also using Staff++ vanish
  hide-vanished: false

storage:
  host: 'localhost'
  user: 'root'
  database: 'root'
  password: 'mypass'
  port: 3306
  max-pool-size: 5
  ssl-enabled: false
